# Generated by Django 3.0.3 on 2020-10-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_management', '0008_postoadministrativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_number', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fdp', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('community', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='call_manager.Ages')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.District')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactor', to='call_manager.Gender')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.Location')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.Province')),
            ],
        ),
    ]
