# Generated by Django 3.0.3 on 2020-10-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("call_manager", "0004_auto_20201016_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.CharField(max_length=25)),
                ("consent_to_share_third_party", models.BooleanField(default=False)),
                (
                    "consent_to_collect_personal_info",
                    models.BooleanField(default=False),
                ),
                ("call_require_feedback", models.BooleanField(default=False)),
                ("call_notes", models.TextField(default="")),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "contactor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="call_manager.Contactor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "how_knows_us",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="call_manager.HowDoYouHearAboutUs",
                    ),
                ),
            ],
        ),
    ]
