# Generated by Django 3.0.3 on 2020-10-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0007_auto_20201020_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
