#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:10.15.3

pipelines:
  branches:
    '{staging}':
      - step:
          name: Build and Test
          deployment: Staging
          caches:
            #- nodeapp
            - yarn
          script:
            - cd app/
            - yarn
            - unset CI
            - yarn build
          artifacts:
            - app/build/**
      - step:
          name: Deploy to S3 Staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
                AWS_DEFAULT_REGION: 'eu-west-1'
                S3_BUCKET: 'staging.linha1458.moz.wfp.org'
                LOCAL_PATH: 'app/build'
                ACL: 'public-read'
      - step:
          name: Invalidate Cloudfront
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
                AWS_DEFAULT_REGION: 'eu-west-1'
                DISTRIBUTION_ID: "E1C66NRLMEV1RM"
    '{production}':
      - step:
          name: Build and Test
          caches:
            #- nodeapp
            - yarn
          script:
            - cd app/
            - yarn
            - unset CI
            - yarn build
          artifacts:
            - app/build/**
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
                AWS_DEFAULT_REGION: 'eu-west-1'
                S3_BUCKET: 'vulavula1458.co.mz'
                LOCAL_PATH: 'app/build'
                ACL: 'public-read'
      - step:
          name: Invalidate Cloudfront
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
                AWS_DEFAULT_REGION: 'eu-west-1'
                DISTRIBUTION_ID: "E2L9NWMRKCT11T"
    '{dev, feature/*}':
      - step:
          name: Build and Test
          deployment: Staging
          caches:
            #- nodeapp
            - yarn
          script:
            - cd app/
            - yarn
            - unset CI
            - yarn build
          artifacts:
            - app/build/**
      - step:
          name: Deploy to S3 Staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-west-1'
                S3_BUCKET: 'lv.client-apps.robobo.org'
                LOCAL_PATH: 'app/build'
                ACL: 'public-read'
      - step:
          name: Invalidate Cloudfront
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-west-1'
                DISTRIBUTION_ID: "E1SNBMWLEO4WTS"
    '{docker-dev}':
      - step:
          script:
            - npm install
            - npm test
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t roboboinc/linhaverde:dev .
            - docker push roboboinc/linhaverde:dev
          services:
            - docker
    '{docker}':
      - step:
          script:
            - npm install
            - npm test
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t roboboinc/linhaverde:latest .
            - docker push roboboinc/linhaverde:latest
          services:
            - docker
definitions:
  caches:
#    nodeapp: ./packages/app/node_modules
    yarn: /usr/local/share/.cache/yarn