#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:10.15.3

pipelines:
  branches:
    staging:
      - step:
          name: Build and Test
          deployment: Staging
          caches:
            #- nodeapp
            - yarn
          script:
            - cd app/
            - yarn
            - unset CI
            - yarn build
          artifacts:
            - app/build/**
      - step:
          name: Deploy to S3 Staging
          deployment: Staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-west-1'
                S3_BUCKET: 'staging.linha1458.moz.wfp.org'
                LOCAL_PATH: 'app/build'
                ACL: 'public-read'
    '{master,dev,feature/*}':
      - step:
          name: Build and Test
          caches:
            #- nodeapp
            - yarn
          script:
            - cd app/
            - yarn
            - unset CI
            - yarn build
          artifacts:
            - app/build/**
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-west-1'
                S3_BUCKET: 'vulavula1458.co.mz'
                LOCAL_PATH: 'app/build'
                ACL: 'public-read'
      - step:
          name: Invalidate Cloudfront
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-west-1'
                DISTRIBUTION_ID: "E2L9NWMRKCT11T"
#        - step:
#            name: Code linting
#            script:
#              - cd app/
#              - npm install eslint
#              - npx eslint .
#            caches:
#              - node
definitions:
  caches:
#    nodeapp: ./packages/app/node_modules
    yarn: /usr/local/share/.cache/yarn