version: '3.4'

x-service-volumes: &service-volumes
  - .:/code

x-service-volumes-node: &service-volumes-node
  - .:/code
  - /app/node_modules
  - ./app:/app

x-database-variables: &database-variables
  DB_HOST: db
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASS: postgres

x-app-variables-env: &app-variables-env
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DATABASE_URL: ${DATABASE_URL}
  ALLOWED_HOSTS: ("*",)
  DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}

x-app-variables-local: &app-variables-local
  <<: *database-variables
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  ALLOWED_HOSTS: ("*",)
  DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
  CHOKIDAR_USEPOLLING: "true"
  $REACT_APP_API_URL: ${REACT_APP_API_URL}
  REACT_APP_CIAM_CLIENT_ID: ${REACT_APP_CIAM_CLIENT_ID}
  REACT_APP_CIAM_STS_AUTH: ${REACT_APP_CIAM_STS_AUTH}
  REACT_APP_CIAM_ROOT_API: ${REACT_APP_CIAM_ROOT_API}
  REACT_APP_PUBLIC_URL: ${REACT_APP_PUBLIC_URL}
  REACT_APP_WS_URL: ${REACT_APP_WS_URL}

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres

services:
  db:
    image: postgres:12-alpine
    container_name: casemangmnt_db
    environment: *database-variables
    # volumes:
    #   - db-data:/var/lib/postgresql/data
  db_migrate:
    build: .
    # image: roboboinc/linhaverde
    command: python db/manage.py migrate
    volumes: *service-volumes
    environment: *app-variables-local
    depends_on:
      - db
  frontend:
    build: ./app
    # image: roboboinc/linhaverde
    container_name: case_management_app_frontend
    command: npm start
    hostname: ${HOSTNAME}
    volumes: *service-volumes-node

    ports:
      - "3000:3000"
    stdin_open: true
    environment: *app-variables-local
    depends_on:
      - db_migrate
      - redis
      - web
  web:
    build: .
    # image: roboboinc/linhaverde
    container_name: case_management_app
    # platform: linux/x86_64    # Building on M1 Chip
    command: python db/manage.py runserver 0.0.0.0:8000 
        # 
        # && cd app/ && npm i -f && cd ..
        # && bash deploy.sh 0.0.3
      
    hostname: ${HOSTNAME}
    volumes: *service-volumes
    ports:
      - "8000:8000"
    environment: *app-variables-local
    depends_on:
      - db_migrate
      - redis
      - db
  redis:
    image: redis:alpine
  # celery:
  #   restart: always
  #   build:
  #     context: .
  #   command: ['celery', '-A', 'web', 'worker', '-l', 'INFO']
  #   volumes: *service-volumes
  #   environment: *app-variables-env
  #   depends_on:
  #     - db
  #     - redis
  #     - web

# volumes:
#   - db-data:/var/lib/postgresql/data