version: '3'
    
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: roboboinc/linhaverde
    container_name: lvbackend-staging
    hostname: ${HOSTNAME}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
