version: '3'
    
services:
  # db:
  #   image: postgres:12-alpine
  #   container_name: casemangmnt_db
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    build: .
    # image: roboboinc/linhaverde
    container_name: case_management_app
    # command: ls && ./runserver.sh
    hostname: ${HOSTNAME}
    volumes:
      - .:/code
    ports:
      - "3002:3000"
      - "8001:8000"
    # depends_on:
    #   - db
