apiVersion: v1
kind: Secret
metadata:
  name: linhaverde-sandbox-secret
type: Opaque
data:
  DJANGO_SECRET_KEY: QGpiKCM2aG1paWooKWtyd2cpYW84dnMkJmNneXA2MzF6OWopKD1iMEA4ZThoYwo=
  DATABASE_URL: cG9zdGdyZXM6Ly92cmd6enl4dHpmaWZ4YTo0YTM0MzFiZGMyNWI2M2FkNWExOTliZGUzMDEyMzM2MTRmZDlmNzZlMTUyNjJjN2YyNDg3MTZmZWY4YmU0ZWFhQGVjMi0zNC0xOTUtMTY5LTI1LmNvbXB1dGUtMS5hbWF6b25hd3MuY29tOjU0MzIvZGQyZDgwcHZzYm50M2Q=
  DJANGO_AWS_ACCESS_KEY_ID: QUtJQVZBWU1ZMkdRQzVQRklJNVY=
  DJANGO_AWS_SECRET_ACCESS_KEY: YzdIdEo5SkJOSVFJM0tTemdHSVRZMC9mdnUxVmxlL0Uzb01qL2dWZA==
  DJANGO_AWS_STORAGE_BUCKET_NAME: bGluaGF2ZXJkZQ==
