# Generated by Django 3.0.3 on 2020-04-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0040_remove_contactor_district'),
        ('location_management', '0003_delete_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
