# Generated by Django 3.1.4 on 2021-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('New Case Comment', 'New Case Comment'), ('Case Forwarding', 'Case Forwarding'), ('New Task', 'New Task'), ('New Task Comment', 'New Task Comment'), ('Case Feedback', 'Case Feedback'), ('New Article', 'New Article')], max_length=250),
        ),
    ]
