# Generated by Django 3.1.4 on 2021-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210630_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='model_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
