# Generated by Django 3.1.4 on 2021-07-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('New Case Comment', 'New Case Comment'), ('Case Forwarding', 'Case Forwarding'), ('New Case Received', 'New Case Received'), ('New Task', 'New Task'), ('New Task Comment', 'New Task Comment'), ('Case Feedback', 'Case Feedback'), ('New Article', 'New Article')], max_length=250),
        ),
    ]
