apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linhaverde-chart.fullname" . }}
  labels:
    app: {{ include "linhaverde-chart.name" . }}
    chart: {{ include "linhaverde-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}