# Generated by Django 3.1.4 on 2020-12-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
