# Generated by Django 3.1.4 on 2021-02-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_location_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='province',
        ),
    ]
