# Generated by Django 3.1.4 on 2021-02-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clusteragency_clusterregion_clustersector'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteragency',
            name='cluster_sector',
            field=models.ForeignKey(blank=True, help_text='cluster_sector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_sector', to='accounts.clustersector', verbose_name='Cluster Sector'),
        ),
        migrations.AddField(
            model_name='clusterregion',
            name='cluster_agency',
            field=models.ForeignKey(blank=True, help_text='cluster_agency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_agency', to='accounts.clusteragency', verbose_name='Cluster Agency'),
        ),
        migrations.AddField(
            model_name='clusterregion',
            name='focalpoints',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
