# Generated by Django 3.1.4 on 2021-02-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210216_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteragency',
            name='cluster_sector',
            field=models.ForeignKey(blank=True, help_text='cluster_sector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_agency', to='accounts.clustersector', verbose_name='Cluster Sector'),
        ),
        migrations.AlterField(
            model_name='clusterregion',
            name='cluster_agency',
            field=models.ForeignKey(blank=True, help_text='cluster_agency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_region', to='accounts.clusteragency', verbose_name='Cluster Agency'),
        ),
    ]
