# Generated by Django 3.1.4 on 2021-02-17 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210216_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterregion',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='cluster_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
