# Generated by Django 3.1.4 on 2021-02-17 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clusterregion_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterregion',
            name='focalpoints',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clusterregion',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='cluster_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
