# Generated by Django 3.1.4 on 2021-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210404_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteragency',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='clusterregion',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
    ]
