# Generated by Django 3.1.4 on 2022-05-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211121_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
