# Generated by Django 3.1.4 on 2022-06-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comment',
        ),
    ]
