# Generated by Django 3.1.4 on 2020-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LvForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('deviceid', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, null=True)),
                ('consent_pi', models.CharField(choices=[('1', 'Consento to collect personal info')], help_text='Consent to collect personal information', max_length=1, verbose_name='Consent to collect personal information')),
                ('consent_share_pi', models.CharField(choices=[('1', 'Consent to share personal information with third parties')], help_text='Consent to share personal information with third parties', max_length=1, verbose_name='Consent to share personal information with third parties')),
                ('fullname', models.TextField(help_text='Full Name', verbose_name='Full Name')),
                ('contact', models.IntegerField(help_text='Contact', verbose_name='Contact')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=6, verbose_name='Gender')),
                ('provincia', models.CharField(choices=[('CodProv', 'Provincia')], help_text='Province', max_length=7, verbose_name='Province')),
                ('distrito', models.CharField(choices=[('CodDist', 'Distrito')], help_text='District', max_length=7, verbose_name='District')),
                ('localidade', models.CharField(choices=[('CodLocal', 'Localidade')], help_text='Locality', max_length=8, verbose_name='Locality')),
                ('community', models.TextField(blank=True, help_text='Community', null=True, verbose_name='Community')),
                ('transfermod', models.CharField(choices=[('1', 'Comida'), ('2', 'Senha de dinheiro'), ('3', 'Dinheiro'), ('4', 'Senha de bens'), ('5', 'Bens Não alimentares'), ('6', 'Irrelevante'), ('7', 'FFA'), ('8', 'Alimentação escolar')], help_text='Transfer modality', max_length=1, verbose_name='Transfer modality')),
                ('category', models.CharField(choices=[('1', 'Positive feedback'), ('2', 'Request for information'), ('3', 'Compaint/negative feedback'), ('4', 'Request for assistance'), ('5', 'Data amendment'), ('6', 'Technical problems'), ('7', 'Other')], max_length=1, verbose_name='Case category')),
                ('subcategory', models.CharField(choices=[('1', 'Other'), ('2', 'SEA'), ('3', 'Quality'), ('4', 'Quantity'), ('5', 'Safety problems'), ('6', 'Abuse of power'), ('7', 'Access'), ('8', 'Lost card'), ('9', 'Assistance card not working'), ('10', 'Money'), ('11', 'Distribution issue'), ('12', 'Exclusion error'), ('13', 'Undignified/ disrespect'), ('14', 'Beneficiary card'), ('15', 'Food'), ('16', 'Use of personal data - who, what, how'), ('17', 'Entitlement'), ('18', 'Services'), ('19', 'FFA Activity'), ('20', 'Targeting criteria'), ('21', 'HR'), ('22', 'Symptoms'), ('23', 'Prevention'), ('24', 'Treatment'), ('25', 'Availability of health services'), ('26', 'Myths'), ('27', 'Government guidance'), ('28', 'Current situaton'), ('29', 'Impact of Covid-19 on program'), ('30', 'NFI'), ('31', 'Flood assistance'), ('32', 'Update HH, personal details'), ('33', 'Delete personal information'), ('34', 'Distribution timing'), ('35', 'Duration of assistance')], max_length=2, verbose_name='Sub-category')),
                ('sector', models.CharField(choices=[('1', 'Resiliência'), ('2', 'INGC'), ('3', 'CCCM'), ('4', 'Protecção'), ('5', 'Proteção contra Exploração e Abuso Sexual'), ('6', 'Proteção a criança'), ('7', 'Saúde'), ('8', 'Educação'), ('9', 'Agua, saneamento e Higiene'), ('10', 'Abrigo'), ('11', 'Violência baseada no gênero'), ('12', 'Segurança Alimentar'), ('13', 'Outro')], max_length=2, verbose_name='Sector')),
                ('call_notes', models.TextField(verbose_name='Call notes')),
                ('call_solution', models.TextField(verbose_name='Call solution')),
                ('case_priority', models.CharField(choices=[('1', 'Medium'), ('2', 'High'), ('3', 'Low')], max_length=1, verbose_name='Case priority')),
                ('case_status', models.CharField(choices=[('1', 'Close case')], max_length=1, verbose_name='Case closed')),
            ],
            options={
                'verbose_name': 'linha verde intake form',
                'verbose_name_plural': 'lvforms',
            },
        ),
    ]
