# Generated by Django 3.1.4 on 2021-01-18 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
