# Generated by Django 3.1.4 on 2021-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0002_lvform_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='distribution_point',
            field=models.CharField(blank=True, help_text='Distribution Point', max_length=255, null=True, verbose_name='Distribution Point'),
        ),
    ]
