# Generated by Django 3.1.4 on 2020-12-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
        ('lv_form', '0003_auto_20201202_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_management.province', verbose_name='Province'),
        ),
    ]
