# Generated by Django 3.1.4 on 2021-01-20 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lv_form', '0004_auto_20210118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.CreateModel(
            name='ForwardToFocalpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date forwarded')),
                ('focalpoint', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Focal Point')),
                ('lvform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lv_form.lvform')),
            ],
            options={
                'verbose_name': 'Forward to Focal Point',
                'verbose_name_plural': 'Forwarded to focal points',
            },
        ),
    ]
