# Generated by Django 3.1.4 on 2020-12-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
        ('lv_form', '0004_auto_20201202_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='distrito',
            field=models.ForeignKey(help_text='District', on_delete=django.db.models.deletion.CASCADE, to='location_management.district', verbose_name='District'),
        ),
    ]
