# Generated by Django 3.1.4 on 2020-12-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
        ('lv_form', '0005_auto_20201202_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='case_status',
            field=models.CharField(blank=True, choices=[('1', 'Close case')], max_length=1, null=True, verbose_name='Case closed'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='localidade',
            field=models.ForeignKey(blank=True, help_text='Locality', null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.location', verbose_name='Locality'),
        ),
    ]
