# Generated by Django 3.1.4 on 2021-01-20 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lv_form', '0005_auto_20210120_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardinginstitution',
            name='isFeedback_aproved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Feedback is approved'),
        ),
        migrations.AddField(
            model_name='forwardinginstitution',
            name='referall_to',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_to', to=settings.AUTH_USER_MODEL, verbose_name='Referral to'),
        ),
        migrations.AlterField(
            model_name='forwardinginstitution',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
