# Generated by Django 3.1.4 on 2021-01-20 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lv_form', '0006_auto_20210120_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForwardToFocalpoint',
            new_name='ForwardCaseToFocalpoint',
        ),
        migrations.AlterModelOptions(
            name='forwardcasetofocalpoint',
            options={},
        ),
    ]
