# Generated by Django 3.1.4 on 2020-12-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0006_auto_20201202_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvform',
            name='deviceid',
        ),
        migrations.RemoveField(
            model_name='lvform',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='lvform',
            name='today',
        ),
        migrations.RemoveField(
            model_name='lvform',
            name='username',
        ),
        migrations.AddField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime', null=True, verbose_name='Datetime Created'),
        ),
    ]
