# Generated by Django 3.1.4 on 2021-01-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0007_auto_20210120_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='lvform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lv_form.lvform'),
        ),
    ]
