# Generated by Django 3.1.4 on 2020-12-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0007_auto_20201202_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime', null=True, verbose_name='Date+Time field'),
        ),
    ]
