# Generated by Django 3.1.4 on 2020-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0008_auto_20201202_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='created_by',
            field=models.IntegerField(blank=True, help_text='User', null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='datetime_modified',
            field=models.DateTimeField(blank=True, help_text='Auto datetime update', null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
    ]
