# Generated by Django 3.1.4 on 2020-12-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0009_auto_20201202_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_feedback', models.TextField(blank=True, null=True, verbose_name='Parceiro Feedback')),
                ('task_feedback', models.TextField(blank=True, null=True, verbose_name='Feedback da tarefa')),
                ('has_feedback', models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=5, null=True, verbose_name='Has feedback')),
                ('lvform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lv_form.lvform')),
            ],
            options={
                'verbose_name': 'casecomment',
                'verbose_name_plural': 'casecomments',
            },
        ),
    ]
