# Generated by Django 3.1.4 on 2021-02-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0009_auto_20210202_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lvform',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'lvforms'},
        ),
    ]
