# Generated by Django 3.1.4 on 2021-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0011_auto_20210203_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='lvform_status',
            field=models.CharField(blank=True, choices=[('1', 'Not started'), ('2', 'In Progress'), ('3', 'Closed')], default='1', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
