# Generated by Django 3.1.4 on 2020-12-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_user'),
        ('lv_form', '0011_auto_20201203_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.user', verbose_name='Created By'),
        ),
    ]
