# Generated by Django 3.1.4 on 2020-12-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_user'),
        ('lv_form', '0012_auto_20201207_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.user', verbose_name='Assigned to'),
        ),
    ]
