# Generated by Django 3.1.4 on 2021-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0012_lvform_lvform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('1', 'Medium'), ('2', 'High'), ('3', 'Low')], default='1', max_length=1, verbose_name='Task priority'),
        ),
    ]
