# Generated by Django 3.1.4 on 2020-12-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0013_auto_20201207_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
    ]
