# Generated by Django 3.1.4 on 2021-02-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0013_task_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='individual_commiting_malpractice',
            field=models.CharField(blank=True, choices=[('1', 'Local Leader'), ('2', 'Community Member'), ('3', 'Humanitarian actor'), ('4', 'Unknown')], default='', help_text='LBL_Individual committing malpractice', max_length=1, null=True, verbose_name='LBL_Individual committing malpractice'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Case is closed', verbose_name='Case Closed'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='case_close_category',
            field=models.CharField(blank=True, choices=[('1', 'With Feedback'), ('2', 'Without Feedback')], max_length=1, null=True, verbose_name='Case close category'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='contact',
            field=models.IntegerField(blank=True, help_text='Contact', null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='fullname',
            field=models.CharField(blank=True, help_text='Full Name', max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
