# Generated by Django 3.1.4 on 2020-12-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0014_auto_20201207_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, help_text='Auto datetime update', null=True, verbose_name='Date updated'),
        ),
    ]
