# Generated by Django 3.1.4 on 2021-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0014_auto_20210204_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='age_group',
            field=models.CharField(choices=[('1', '17 and below'), ('2', '18 - 59'), ('3', '60 and above'), ('4', 'Not disclosed')], default='4', help_text='Age', max_length=1, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='call_solution',
            field=models.TextField(blank=True, null=True, verbose_name='Call solution'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='contact_group',
            field=models.CharField(blank=True, choices=[('1', 'Beneficiary'), ('2', 'Representative of beneficiary'), ('3', 'Non beneficiary'), ('4', 'Community leader'), ('5', 'Humanitarian partner'), ('6', 'Other')], max_length=1, null=True, verbose_name='Who is contacting'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, help_text='Case is closed', null=True, verbose_name='Case Closed'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='sector',
            field=models.CharField(choices=[('1', 'Shelter'), ('2', 'WASH'), ('3', 'Education'), ('4', 'Food Security'), ('5', 'Health'), ('6', 'Child Protection'), ('7', 'Gender-based violence'), ('8', 'Protection from Sexual Exploitation and Abuse'), ('9', 'Protection'), ('10', 'CCCM'), ('11', 'Resilience'), ('12', 'INGD'), ('13', 'IDP Registration'), ('14', 'Social Protection/INAS'), ('15', 'Other')], max_length=2, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='transfermod',
            field=models.CharField(blank=True, choices=[('1', 'Food'), ('2', 'Value voucher'), ('3', 'Money'), ('4', 'Commodity voucher'), ('5', 'Non-food Items'), ('6', 'Not relevant'), ('7', 'FFA'), ('8', 'School feeding')], help_text='Transfer modality', max_length=1, null=True, verbose_name='Transfer modality'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='vulnerability',
            field=models.CharField(choices=[('1', 'Person with disability'), ('2', 'Child headed household'), ('3', 'Single parent'), ('4', 'Pregnant or lactating woman'), ('5', 'Elderly head of household'), ('6', 'Chronic patient'), ('7', 'None'), ('8', 'Other')], help_text='Vulnerability', max_length=1, verbose_name='Vulnerability'),
        ),
    ]
