# Generated by Django 3.1.4 on 2020-12-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0015_auto_20201207_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
    ]
