# Generated by Django 3.1.4 on 2021-02-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0015_auto_20210204_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='sector',
            field=models.CharField(choices=[('1', 'Shelter'), ('2', 'WASH'), ('3', 'Education'), ('4', 'Food Security'), ('5', 'Health'), ('6', 'Child Protection'), ('7', 'Gender-based violence'), ('8', 'Protection from Sexual Exploitation and Abuse'), ('9', 'Protection'), ('10', 'CCCM'), ('12', 'INGD'), ('13', 'IDP Registration'), ('14', 'Social Protection/INAS'), ('15', 'Other')], max_length=2, verbose_name='Sector'),
        ),
    ]
