# Generated by Django 3.1.4 on 2021-02-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210216_1235'),
        ('lv_form', '0017_forwardcasetofocalpoint_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardcasetofocalpoint',
            name='cluster_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clusteragency', verbose_name='Cluster Agency'),
        ),
        migrations.AddField(
            model_name='forwardcasetofocalpoint',
            name='cluster_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clusterregion', verbose_name='Cluster Region'),
        ),
        migrations.AddField(
            model_name='forwardcasetofocalpoint',
            name='cluster_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clustersector', verbose_name='Cluster Sector'),
        ),
    ]
