# Generated by Django 3.1.4 on 2020-12-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_user'),
        ('lv_form', '0018_auto_20201207_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecomment',
            name='has_feedback',
        ),
        migrations.RemoveField(
            model_name='casecomment',
            name='partner_feedback',
        ),
        migrations.RemoveField(
            model_name='casecomment',
            name='task_feedback',
        ),
        migrations.RemoveField(
            model_name='task',
            name='partner_feedback',
        ),
        migrations.AddField(
            model_name='casecomment',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='task',
            name='call_attempts',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of attempts to reach the other person'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(blank=True, choices=[('1', 'Request for information'), ('2', 'Send Feedback')], max_length=1, null=True, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='casecomment',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='forwardinginstitution',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='datetime_updated',
            field=models.DateTimeField(blank=True, help_text='Auto datetime update', null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_created',
            field=models.DateTimeField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
    ]
