# Generated by Django 3.1.4 on 2021-02-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_tipology', '0001_initial'),
        ('lv_form', '0019_auto_20210217_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_tipology.subcategory', verbose_name='Sub-category'),
        ),
    ]
