# Generated by Django 3.1.4 on 2020-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0019_auto_20201207_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='community',
            field=models.CharField(blank=True, help_text='Community', max_length=255, null=True, verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='fullname',
            field=models.CharField(help_text='Full Name', max_length=255, verbose_name='Full Name'),
        ),
    ]
