# Generated by Django 3.1.4 on 2021-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0022_auto_20210317_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='case_close_category',
            field=models.CharField(blank=True, choices=[('With Feedback', 'With Feedback'), ('Without Feedback', 'Without Feedback')], max_length=100, null=True, verbose_name='Case close category'),
        ),
    ]
