# Generated by Django 3.1.4 on 2020-12-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0002_user'),
        ('lv_form', '0022_auto_20201207_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='forwardinginstitution',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, help_text='Auto datetime update', null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='location_management.user', verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='location_management.user', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto datetime Create', null=True, verbose_name='Date created'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('datetime_created', models.DateTimeField(blank=True, help_text='Auto datetime Create', null=True, verbose_name='Date created')),
                ('created_by', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to='location_management.user', verbose_name='Created By')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lv_form.task')),
            ],
            options={
                'verbose_name': 'taskcomment',
                'verbose_name_plural': 'taskcomments',
            },
        ),
    ]
