# Generated by Django 3.1.4 on 2020-12-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_tipology', '0005_auto_20201209_1037'),
        ('lv_form', '0023_auto_20201207_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='age_group',
            field=models.CharField(blank=True, choices=[('1', '17 e menos'), ('2', '18 - 59'), ('3', '60 e acima'), ('4', 'Nao mencionado')], help_text='Age', max_length=1, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='call_feedback',
            field=models.CharField(blank=True, choices=[('1', 'Muito Satisfeito'), ('2', 'Satisfeito'), ('3', 'Neutro'), ('4', 'Insatisfeito'), ('5', 'Muito insatisfeito')], help_text='How do you feel about how your query was dealt with during this call?', max_length=1, null=True, verbose_name='How do you feel about how your query was dealt with during this call?'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='callback_required',
            field=models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Callback required?', max_length=5, null=True, verbose_name='Callback required?'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='contact_group',
            field=models.CharField(choices=[('1', 'Beneficiario'), ('2', 'Alguem para beneficiario'), ('3', 'Nao beneficiario'), ('4', 'Lider comunitario'), ('5', 'Parceiro Humanitario'), ('6', 'Outro')], default=1, max_length=1, verbose_name='Who is contacting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lvform',
            name='distribution_point',
            field=models.TextField(blank=True, help_text='Distribution Point', null=True, verbose_name='Distribution Point'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='how_callback',
            field=models.CharField(blank=True, choices=[('1', 'Mesmo contacto'), ('2', 'Outro contacto')], help_text='How would you prefer to be reached?', max_length=1, null=True, verbose_name='How would you prefer to be reached?'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='how_knows_lv',
            field=models.CharField(blank=True, choices=[('1', 'Radio'), ('2', 'Panfletos'), ('3', 'Pessoas trabalhando na comunidade'), ('4', 'SMS'), ('5', 'Cartazes ou material de visibilidade'), ('6', 'Caixa de sugestoes')], help_text='How have you come to know about the complaints and feedback mechanism?', max_length=1, null=True, verbose_name='How have you come to know about the complaints and feedback mechanism?'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='location_type',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Nao'), ('3', 'Irrelevant')], help_text='Accommodation or resettlement centre', max_length=1, null=True, verbose_name='Accommodation or resettlement centre'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='means_of_communication',
            field=models.CharField(blank=True, choices=[('1', 'Linha verde (proprio numero)'), ('2', 'Linha verde (telefone emprestado)'), ('3', 'WFP hotline (proprio numero)'), ('4', 'WFP hotline (telefone emprestado)'), ('5', 'Mesa de apoio'), ('6', 'sms'), ('7', 'Email'), ('8', 'Caixa de sugestoes')], help_text='Means of Communication', max_length=1, null=True, verbose_name='Means of Communication'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='other_contact',
            field=models.IntegerField(blank=True, help_text='Contact', null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='ressetlement_name',
            field=models.CharField(blank=True, help_text='Resettlement name', max_length=255, null=True, verbose_name='Resettlement name'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='subcategory_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_tipology.subcategoryissue', verbose_name='Sub-category issue'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='unavailable_contact',
            field=models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Contact was unavailable for feedback', max_length=5, null=True, verbose_name='Contact was unavailable for feedback'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='vulnerability',
            field=models.CharField(choices=[('1', 'Pessoa com dificiencia'), ('2', 'Familia chefiada por crianca'), ('3', 'Pais solteiros'), ('4', 'Mulher gravida ou lactente'), ('5', 'Familia chefiada por idosos'), ('6', 'Doente Cronico'), ('7', 'Nenhum'), ('8', 'Outro')], default=1, help_text='Vulnerability', max_length=1, verbose_name='Vulnerability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lvform',
            name='who_not_receiving',
            field=models.CharField(blank=True, choices=[('1', 'Individual'), ('2', 'Community')], help_text='Person not receiving', max_length=1, null=True, verbose_name='Who is not receiving assistance'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.casetipology', verbose_name='Case category'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Not specified')], help_text='Gender', max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.subcategory', verbose_name='Sub-category'),
        ),
    ]
