# Generated by Django 3.1.4 on 2021-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0023_auto_20210317_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='lvform_status',
            field=models.CharField(blank=True, choices=[('Not started', 'Not started'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='1', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
