# Generated by Django 3.1.4 on 2021-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0024_auto_20210317_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='case_priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('High', 'High'), ('Low', 'Low')], max_length=50, verbose_name='Case priority'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='sector',
            field=models.CharField(choices=[('Shelter', 'Shelter'), ('WASH', 'WASH'), ('Education', 'Education'), ('Food Security', 'Food Security'), ('Health', 'Health'), ('Child Protection', 'Child Protection'), ('Gender-based violence', 'Gender-based violence'), ('PSEA', 'Protection from Sexual Exploitation and Abuse'), ('Protection', 'Protection'), ('CCCM', 'CCCM'), ('INGD', 'INGD'), ('IDP Registration', 'IDP Registration'), ('Social Protection/INAS', 'Social Protection/INAS'), ('Other', 'Other')], max_length=100, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='vulnerability',
            field=models.CharField(choices=[('Person with disability', 'Person with disability'), ('Child headed household', 'Child headed household'), ('Single parent', 'Single parent'), ('Pregnant or lactating woman', 'Pregnant or lactating woman'), ('Elderly head of household', 'Elderly head of household'), ('Chronic patient', 'Chronic patient'), ('None', 'None'), ('Other', 'Other')], help_text='Vulnerability', max_length=100, verbose_name='Vulnerability'),
        ),
    ]
