# Generated by Django 3.1.4 on 2020-12-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0024_auto_20201209_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardinginstitution',
            name='has_feedback',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has feedback'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='callback_required',
            field=models.BooleanField(blank=True, default=False, help_text='Callback required?', null=True, verbose_name='Callback required?'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='consent_pi',
            field=models.BooleanField(default=False, help_text='Consent to collect personal information', verbose_name='Consent to collect personal information'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='consent_share_pi',
            field=models.BooleanField(default=False, help_text='Consent to share personal information with third parties', verbose_name='Consent to share personal information with third parties'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='unavailable_contact',
            field=models.BooleanField(blank=True, default=False, help_text='Contact was unavailable for feedback', null=True, verbose_name='Contact was unavailable for feedback'),
        ),
    ]
