# Generated by Django 3.1.4 on 2021-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0026_auto_20210317_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not relevant', 'Not relevant')], help_text='Accommodation or resettlement centre', max_length=20, null=True, verbose_name='Accommodation or resettlement centre'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='who_not_receiving',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Community', 'Community')], help_text='Person not receiving', max_length=20, null=True, verbose_name='Who is not receiving assistance'),
        ),
    ]
