# Generated by Django 3.1.4 on 2021-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0027_auto_20210317_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='transfermod',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Value voucher', 'Value voucher'), ('Money', 'Money'), ('Commodity voucher', 'Commodity voucher'), ('NFI', 'Non-food Items'), ('Not relevant', 'Not relevant'), ('FFA', 'FFA'), ('School feeding', 'School feeding')], help_text='Transfer modality', max_length=50, null=True, verbose_name='Transfer modality'),
        ),
    ]
