# Generated by Django 3.1.4 on 2021-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0029_auto_20210317_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='contact_group',
            field=models.CharField(blank=True, choices=[('Beneficiary', 'Beneficiary'), ('Representative of beneficiary', 'Representative of beneficiary'), ('Non beneficiary', 'Non beneficiary'), ('Community leader', 'Community leader'), ('Humanitarian partner', 'Humanitarian partner'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Who is contacting'),
        ),
    ]
