# Generated by Django 3.1.4 on 2021-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0030_auto_20210317_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='how_knows_lv',
            field=models.CharField(blank=True, choices=[('Radio', 'Radio'), ('Pamphlet', 'Pamphlet'), ('People working in the community', 'People working in the community'), ('SMS', 'SMS'), ('Posters or other visibility material', 'Posters or other visibility material'), ('Suggestion box', 'Suggestion box')], help_text='How did you hear about linha verde?', max_length=50, null=True, verbose_name='How did you hear about linha verde?'),
        ),
    ]
