# Generated by Django 3.1.4 on 2021-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0031_auto_20210317_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='how_callback',
            field=models.CharField(blank=True, choices=[('Same phone', 'Same phone'), ('Other phone', 'Other phone')], help_text='How would you like to be contacted?', max_length=20, null=True, verbose_name='How would you like to be contacted?'),
        ),
    ]
