# Generated by Django 3.1.4 on 2021-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0033_auto_20210317_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(blank=True, choices=[('Request for information', 'Request for information'), ('Send Feedback', 'Send Feedback')], max_length=30, null=True, verbose_name='Task Title'),
        ),
    ]
