# Generated by Django 3.1.4 on 2021-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0034_auto_20210317_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvform',
            name='case_priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('High', 'High'), ('Low', 'Low')], default='Medium', max_length=50, verbose_name='Case priority'),
        ),
        migrations.AlterField(
            model_name='lvform',
            name='lvform_status',
            field=models.CharField(blank=True, choices=[('Not started', 'Not started'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Not started', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
