# Generated by Django 3.1.4 on 2021-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0036_auto_20210322_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecomment',
            name='feedback',
            field=models.TextField(default='', verbose_name='Feedback'),
        ),
    ]
