# Generated by Django 3.1.4 on 2021-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0037_auto_20210329_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
    ]
