# Generated by Django 3.1.4 on 2021-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0038_lvform_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='othercategory',
            field=models.CharField(blank=True, help_text='Other category', max_length=255, null=True, verbose_name='Other category'),
        ),
        migrations.AddField(
            model_name='lvform',
            name='response',
            field=models.CharField(blank=True, help_text='Response', max_length=255, null=True, verbose_name='Response'),
        ),
    ]
