# Generated by Django 3.1.4 on 2021-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0039_auto_20210506_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvform',
            name='month',
            field=models.CharField(blank=True, help_text='Month', max_length=255, null=True, verbose_name='Month'),
        ),
    ]
