# Generated by Django 3.1.4 on 2021-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv_form', '0040_lvform_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardcasetofocalpoint',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='forwardinginstitution',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
    ]
