apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linhaverde-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - lv2.robobo.org
    secretName: linhaverde-production-tls-secret
  rules:
    - host: lv2.robobo.org
      http:
        paths:
          - backend:
              serviceName: linhaverde-chart
              servicePort: 80
            path: /
