apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lv-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
#  tls:
#  - hosts:
#    - lv2.robobo.org
#    secretName: linhaverde-production-tls-secret
  rules:
    - host: backend.lv-staging.robobo.org
      http:
        paths:
          - backend:
              serviceName: lv-chart
              servicePort: 80
            path: /
