# Generated by Django 3.0.3 on 2020-02-25 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_note', models.TextField(max_length=1000)),
                ('camp', models.TextField(choices=[('Y', 'YES'), ('N', 'NO')])),
                ('caller_not_reached_for_feedback', models.BooleanField(blank=True, default=True, null=True)),
                ('case_closed', models.BooleanField(default=False)),
                ('case_id', models.TextField(max_length=20, unique=True)),
                ('case_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('community_member', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('humanitarion_actor', models.TextField(max_length=200)),
                ('local_leader', models.TextField(max_length=200)),
                ('other_vulnerabilites', models.TextField(blank=True, max_length=200, null=True)),
                ('resettlement_name', models.TextField(blank=True, max_length=200, null=True)),
                ('resolution_callback', models.BooleanField(default=False)),
                ('soluction', models.TextField(max_length=1000)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('vulnerabilites', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HowDoYouHearAboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HowWouldYouLikeToBeContacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReferallEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='case_manager.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('resolution_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_subcategory', to='case_manager.ResolutionCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(blank=True, default='')),
                ('alternative_number', models.TextField(blank=True, default='', null=True)),
                ('contact', models.TextField(max_length=100)),
                ('fdp', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('full_name', models.TextField(max_length=300)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.Community')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.District')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactor', to='case_manager.Gender')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.Location')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactor', to='location_management.Province')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='case_manager.Case')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='case_manager.Category')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='case_manager.TaskStatus')),
            ],
        ),
        migrations.CreateModel(
            name='CaseReferall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=1000)),
                ('refered_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_referall', to='case_manager.Case')),
                ('referall_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_referall', to='case_manager.ReferallEntity')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_manager.CasePriority'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_manager.Category'),
        ),
        migrations.AddField(
            model_name='case',
            name='contactor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_manager.Contactor'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='how_knows_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_manager.HowDoYouHearAboutUs'),
        ),
        migrations.AddField(
            model_name='case',
            name='sub_category',
            field=models.ManyToManyField(null=True, related_name='cases', to='case_manager.SubCategory'),
        ),
    ]
