# Generated by Django 3.0.3 on 2020-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='camp',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='local_leader',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='other_vulnerabilites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='resettlement_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='vulnerabilites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='casepriority',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='age',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='alternative_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='fdp',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='full_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customersatisfaction',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='howdoyouhearaboutus',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='howwouldyouliketobecontacted',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='referallentity',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='referallentity',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='resolutioncategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resolutionsubcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategoryissue',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
