# Generated by Django 3.0.3 on 2020-03-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0002_auto_20200305_0829"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="humanitarion_actor",
            new_name="humanitarian_actor",
        ),
    ]
