# Generated by Django 3.0.3 on 2020-03-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0004_auto_20200305_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.Programme'),
        ),
    ]
