# Generated by Django 3.0.3 on 2020-03-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0005_case_programme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="programme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="case_manager.Programme",
            ),
        ),
    ]
