# Generated by Django 3.0.3 on 2020-03-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0006_auto_20200305_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="how_would_you_like_to_be_contacted",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="case_manager.HowWouldYouLikeToBeContacted",
            ),
        ),
    ]
