# Generated by Django 3.0.3 on 2020-03-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0007_case_how_would_you_like_to_be_contacted"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetask",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
