# Generated by Django 3.0.3 on 2020-03-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0008_casetask_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfereModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='transfere_modality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_manager.TransfereModality'),
        ),
    ]
