# Generated by Django 3.0.3 on 2020-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0009_auto_20200309_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='consent_to_collect_personal_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='consent_to_share_third_party',
            field=models.BooleanField(default=False),
        ),
    ]
