# Generated by Django 3.0.3 on 2020-03-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0010_auto_20200309_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='customer_satisfaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_manager.CustomerSatisfaction'),
        ),
    ]
