# Generated by Django 3.0.3 on 2020-03-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0011_case_customer_satisfaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="MecanismUsed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="mecanism_used",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="case_manager.MecanismUsed",
            ),
        ),
    ]
