# Generated by Django 3.0.3 on 2020-03-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0012_auto_20200309_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoryIssue',
            new_name='CategoryIssue',
        ),
    ]
