# Generated by Django 3.0.3 on 2020-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0014_auto_20200310_0738"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="category_issue_sub",
        ),
        migrations.AddField(
            model_name="case",
            name="category_issue_sub",
            field=models.ManyToManyField(
                null=True, related_name="cases", to="case_manager.CategoryIssueSub"
            ),
        ),
    ]
