# Generated by Django 3.0.3 on 2020-03-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0015_auto_20200310_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category_issue_sub',
            field=models.ManyToManyField(related_name='cases', to='case_manager.CategoryIssueSub'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sub_category',
            field=models.ManyToManyField(related_name='cases', to='case_manager.SubCategory'),
        ),
    ]
