# Generated by Django 3.0.3 on 2020-03-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0016_auto_20200310_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereferall',
            name='has_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
