# Generated by Django 3.0.3 on 2020-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0019_case_case_forwarded"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="casetask", name="category",),
    ]
