# Generated by Django 3.0.3 on 2020-03-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0021_casetask_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereferall",
            name="feedback",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
