# Generated by Django 3.0.3 on 2020-03-13 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_manager', '0023_auto_20200311_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='referallentity',
            name='users',
            field=models.ManyToManyField(related_name='referall_entity', to=settings.AUTH_USER_MODEL),
        ),
    ]
