# Generated by Django 3.0.3 on 2020-03-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0025_auto_20200316_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='soluction',
            new_name='solution',
        ),
    ]
