# Generated by Django 3.0.3 on 2020-03-19 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0026_auto_20200319_0840"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetask",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 3, 19, 8, 53, 11, 289682, tzinfo=utc)
            ),
        ),
    ]
