# Generated by Django 3.0.3 on 2020-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0027_casetask_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
