# Generated by Django 3.0.3 on 2020-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0029_casetask_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
