# Generated by Django 3.0.3 on 2020-04-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0035_auto_20200324_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactor',
            name='age',
        ),
    ]
