# Generated by Django 3.0.3 on 2020-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0037_auto_20200401_0823"),
    ]

    operations = [
        migrations.AddField(
            model_name="casereferall",
            name="referred_to_focal_point",
            field=models.BooleanField(default=False),
        ),
    ]
