# Generated by Django 3.0.3 on 2020-04-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0038_casereferall_referred_to_focal_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactor',
            name='community',
            field=models.CharField(default='', max_length=100),
        ),
    ]
