# Generated by Django 3.0.3 on 2020-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        ("case_manager", "0040_remove_contactor_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="focal_points",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="user_management.FocalPointProfile"
            ),
        ),
    ]
