# Generated by Django 3.0.3 on 2020-04-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0041_case_focal_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="focal_point_notes",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="casetask",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="casetask",
            name="task_feedback",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
