# Generated by Django 3.0.3 on 2020-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0042_auto_20200414_0944"),
    ]

    operations = [
        migrations.AddField(
            model_name="casereferall",
            name="comments",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="casereferall",
            name="is_valid_feedback",
            field=models.BooleanField(default=False),
        ),
    ]
