# Generated by Django 3.0.3 on 2020-04-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0045_auto_20200415_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetask",
            name="gestor_comments",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="casetask",
            name="task_feedback",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="casetask",
            name="title",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
