# Generated by Django 3.0.3 on 2020-04-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0047_casecomments"),
    ]

    operations = [
        migrations.AddField(
            model_name="casecomments",
            name="referall_entity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="case_manager.ReferallEntity",
            ),
        ),
    ]
