# Generated by Django 3.0.3 on 2020-04-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0048_casecomments_referall_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casecomments",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="case_manager.Case",
            ),
        ),
    ]
