# Generated by Django 3.0.3 on 2020-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0050_casecomments_has_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category_issue_sub',
        ),
        migrations.AddField(
            model_name='case',
            name='received_assistence',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CategoryIssueSub',
        ),
    ]
