# Generated by Django 3.0.3 on 2020-04-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0054_case_other_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryissue",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="case_manager.SubCategory",
            ),
        ),
    ]
