# Generated by Django 3.0.3 on 2020-04-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0055_categoryissue_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualCommitedFraud",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_manager.SubCategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="individual_commited_fraud",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="case_manager.IndividualCommitedFraud",
            ),
        ),
    ]
