# Generated by Django 3.0.3 on 2020-04-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0057_auto_20200422_1612"),
    ]

    operations = [
        migrations.RemoveField(model_name="case", name="sub_category",),
        migrations.AddField(
            model_name="case",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="case_manager.SubCategory",
            ),
        ),
    ]
