# Generated by Django 3.0.3 on 2020-04-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0061_casetask_attemptes_to_call_without_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetask',
            name='task_category',
        ),
    ]
