# Generated by Django 3.0.3 on 2020-04-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0062_remove_casetask_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="casereferall",
            name="have_focal_point_feedback",
            field=models.BooleanField(default=False),
        ),
    ]
