# Generated by Django 3.0.3 on 2020-04-29 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("case_manager", "0063_casereferall_have_focal_point_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskCategory",
        ),
    ]
