# Generated by Django 3.0.3 on 2020-05-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0007_district'),
        ('case_manager', '0063_casereferall_have_focal_point_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactor',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.District'),
        ),
    ]
