# Generated by Django 3.0.3 on 2020-04-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0064_auto_20200429_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
