# Generated by Django 3.0.3 on 2020-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0066_auto_20200429_1547"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="call_note",
            field=models.TextField(blank="", default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="case",
            name="solution",
            field=models.TextField(blank="", default="", max_length=1000),
        ),
    ]
