# Generated by Django 3.0.3 on 2020-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0071_case_how_case_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='how_case_close',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
