# Generated by Django 3.0.3 on 2020-05-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0072_auto_20200513_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
