# Generated by Django 3.0.3 on 2020-05-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0073_auto_20200514_0646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryissue",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
