# Generated by Django 3.0.3 on 2020-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0074_auto_20200518_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_call',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
    ]
