# Generated by Django 3.0.3 on 2020-06-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0075_case_case_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="camp",
            field=models.CharField(
                choices=[("Y", "YES"), ("N", "NO"), ("NR", "NOT RELEVANT")],
                default="N",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="contactor",
            name="contact",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contactor",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
