# Generated by Django 3.0.3 on 2020-08-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0008_postoadministrativo'),
        ('case_manager', '0075_case_case_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='camp',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO'), ('NR', 'NOT RELEVANT')], default='N', max_length=25),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactor', to='location_management.Province'),
        ),
    ]
