# Generated by Django 3.0.3 on 2020-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0077_auto_20200610_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_at_db',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='camp',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO'), ('NR', 'NOT RELEVANT')], default='N', max_length=25),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
