# Generated by Django 3.0.3 on 2020-06-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0076_auto_20200609_0651'),
        ('case_manager', '0077_auto_20200610_1132'),
    ]

    operations = [
    ]
