# Generated by Django 3.0.3 on 2020-10-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_manager", "0002_customersatisfaction"),
        ("case_manager", "0077_auto_20201016_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="customer_satisfaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="call_manager.CustomerSatisfaction",
            ),
        ),
        migrations.DeleteModel(
            name="CustomerSatisfaction",
        ),
    ]
