# Generated by Django 3.0.3 on 2020-08-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0078_auto_20200617_0950'),
        ('case_manager', '0077_auto_20200616_1146'),
    ]

    operations = [
    ]
