# Generated by Django 3.0.3 on 2020-10-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0079_auto_20201016_1050"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="consent_to_collect_personal_info",
        ),
        migrations.RemoveField(
            model_name="case",
            name="consent_to_share_third_party",
        ),
        migrations.RemoveField(
            model_name="case",
            name="how_knows_us",
        ),
    ]
