# Generated by Django 3.0.3 on 2020-10-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0080_auto_20201016_1147"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="customer_satisfaction",
        ),
    ]
