# Generated by Django 3.0.3 on 2020-10-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0007_auto_20201020_0912'),
        ('location_management', '0008_postoadministrativo'),
        ('case_manager', '0081_remove_case_customer_satisfaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_forwarded',
            new_name='case_forward',
        ),
        migrations.RemoveField(
            model_name='case',
            name='call_note',
        ),
        migrations.RemoveField(
            model_name='case',
            name='call_require_aditional_information',
        ),
        migrations.RemoveField(
            model_name='case',
            name='call_require_callback_for_feedback',
        ),
        migrations.RemoveField(
            model_name='case',
            name='caller_not_reached_for_feedback',
        ),
        migrations.RemoveField(
            model_name='case',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_call',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_uuid',
        ),
        migrations.RemoveField(
            model_name='case',
            name='category_issue',
        ),
        migrations.RemoveField(
            model_name='case',
            name='contactor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='focal_point_notes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='how_case_close',
        ),
        migrations.RemoveField(
            model_name='case',
            name='how_case_was_closed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='how_would_you_like_to_be_contacted',
        ),
        migrations.RemoveField(
            model_name='case',
            name='individual_commited_fraud',
        ),
        migrations.RemoveField(
            model_name='case',
            name='mecanism_used',
        ),
        migrations.RemoveField(
            model_name='case',
            name='other_category',
        ),
        migrations.RemoveField(
            model_name='case',
            name='other_sources',
        ),
        migrations.RemoveField(
            model_name='case',
            name='other_vulnerabilites',
        ),
        migrations.RemoveField(
            model_name='case',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='case',
            name='received_assistence',
        ),
        migrations.RemoveField(
            model_name='case',
            name='resettlement_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='response_program',
        ),
        migrations.RemoveField(
            model_name='case',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='case',
            name='source_of_information',
        ),
        migrations.RemoveField(
            model_name='case',
            name='transfere_modality',
        ),
        migrations.RemoveField(
            model_name='case',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='case',
            name='vulnerability',
        ),
        migrations.RemoveField(
            model_name='case',
            name='who_is_never_received_assistance',
        ),
        migrations.AddField(
            model_name='case',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='call_manager.Call'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_manager.CasePriority'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='case_manager.CaseStatus'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_manager.Category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PersonsInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('address_reference', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('age', models.CharField(default='', max_length=3)),
                ('community', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_involved', to='location_management.District')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_involved', to='call_manager.Gender')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_involved', to='location_management.Location')),
                ('person_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_involved', to='case_manager.PersonType')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_involved', to='location_management.Province')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='persons_involved',
            field=models.ManyToManyField(related_name='cases', to='case_manager.PersonsInvolved'),
        ),
    ]
