# Generated by Django 3.0.3 on 2020-10-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0083_auto_20201021_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereferall",
            name="feedback",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="extrafields",
            name="parent_name",
            field=models.CharField(blank="", default="", max_length=200),
        ),
    ]
