# Generated by Django 3.0.3 on 2020-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0084_auto_20201021_1501"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafields",
            name="parent_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
