# Generated by Django 3.0.3 on 2020-10-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0085_auto_20201021_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_field_option_value', to='case_manager.ExtraFields'),
        ),
    ]
