# Generated by Django 3.0.3 on 2020-10-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0087_fieldvalue_contactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalue',
            name='call',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='case',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='contactor',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='field',
        ),
        migrations.DeleteModel(
            name='ExtraFieldOptions',
        ),
        migrations.DeleteModel(
            name='ExtraFields',
        ),
        migrations.DeleteModel(
            name='FieldValue',
        ),
    ]
