# Generated by Django 3.0.3 on 2020-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0088_auto_20201022_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereferall",
            name="feedback",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
