# Generated by Django 3.0.3 on 2020-11-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("call_manager", "0009_auto_20201102_0941"),
        ("case_manager", "0090_auto_20201102_0945"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="contactor",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="call_manager.Contactor",
            ),
        ),
    ]
