# Generated by Django 3.0.3 on 2020-11-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0093_casereferall_focal_point_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_classification', to='case_manager.Category')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='case_manager.CaseClassification'),
        ),
    ]
