# Generated by Django 3.0.3 on 2020-04-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostLanguage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="active_revision",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="expiration_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="external_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts_management.PostLanguage",
            ),
        ),
    ]
