# Generated by Django 3.0.3 on 2020-04-28 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_management', '0004_auto_20200428_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aproved_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_aprovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='assigned_to',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
