# Generated by Django 3.0.3 on 2020-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form_extra_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafields",
            name="table_name",
            field=models.CharField(
                choices=[
                    ("call", "call"),
                    ("contactor", "contactor"),
                    ("case", "case"),
                ],
                max_length=200,
            ),
        ),
    ]
