# Generated by Django 3.0.3 on 2020-11-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("case_manager", "0090_auto_20201102_0945"),
        ("call_manager", "0009_auto_20201102_0941"),
        ("form_extra_manager", "0002_auto_20201029_1413"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldvalue",
            name="call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extra_fields",
                to="call_manager.Call",
            ),
        ),
        migrations.AlterField(
            model_name="fieldvalue",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extra_fields",
                to="case_manager.Case",
            ),
        ),
        migrations.AlterField(
            model_name="fieldvalue",
            name="contactor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extra_fields",
                to="call_manager.Contactor",
            ),
        ),
    ]
