# Generated by Django 3.1.4 on 2021-02-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lv_form', '0019_auto_20210217_0617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name', max_length=255, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(default='')),
                ('language', models.CharField(blank=True, choices=[('pt', 'Portuguese'), ('en', 'English')], max_length=2, null=True, verbose_name='Language')),
                ('file', models.FileField(upload_to='documents')),
                ('published_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('active_revision', models.BooleanField(default=False)),
                ('external_link', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('aproved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_aprovers', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_assignment', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('lvform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lv_form.lvform')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
