# Generated by Django 3.1.4 on 2021-05-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210322_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Is Deleted', null=True, verbose_name='Is Deleted'),
        ),
    ]
