# Generated by Django 3.1.4 on 2021-07-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articlefiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleFiles',
            new_name='ArticleFile',
        ),
    ]
