# Generated by Django 3.1.4 on 2020-12-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTipology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(help_text='Case Category', verbose_name='Case Category')),
            ],
            options={
                'verbose_name': 'linha verde case tipology',
                'verbose_name_plural': 'casetipologys',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.TextField(help_text='Sub Category', verbose_name='Sub Category')),
                ('casetipology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.casetipology')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategorys',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_issue', models.TextField(help_text='Sub Category Issue', verbose_name='Sub Category Issue')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.subcategory')),
            ],
            options={
                'verbose_name': 'subcategoryissue',
                'verbose_name_plural': 'subcategoryissues',
            },
        ),
    ]
