# Generated by Django 3.1.4 on 2020-12-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTipology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Positive feedback'), ('2', 'Request for information'), ('3', 'Compaint/negative feedback'), ('4', 'Request for assistance'), ('5', 'Data amendment'), ('6', 'Technical problems'), ('7', 'Other')], help_text='Case Category', max_length=1, verbose_name='Case Category')),
            ],
            options={
                'verbose_name': 'linha verde case tipology',
                'verbose_name_plural': 'casetipologys',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(choices=[('1', 'Other'), ('2', 'SEA'), ('3', 'Quality'), ('4', 'Quantity'), ('5', 'Safety problems'), ('6', 'Abuse of power'), ('7', 'Access'), ('8', 'Lost card'), ('9', 'Assistance card not working'), ('10', 'Money'), ('11', 'Distribution issue'), ('12', 'Exclusion error'), ('13', 'Undignified/ disrespect'), ('14', 'Beneficiary card'), ('15', 'Food'), ('16', 'Use of personal data - who, what, how'), ('17', 'Entitlement'), ('18', 'Services'), ('19', 'FFA Activity'), ('20', 'Targeting criteria'), ('21', 'HR'), ('22', 'Symptoms'), ('23', 'Prevention'), ('24', 'Treatment'), ('25', 'Availability of health services'), ('26', 'Myths'), ('27', 'Government guidance'), ('28', 'Current situaton'), ('29', 'Impact of Covid-19 on program'), ('30', 'NFI'), ('31', 'Flood assistance'), ('32', 'Update HH, personal details'), ('33', 'Delete personal information'), ('34', 'Distribution timing'), ('35', 'Duration of assistance')], help_text='Sub Category', max_length=2, verbose_name='Sub Category')),
                ('casetipology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.casetipology')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategorys',
            },
        ),
    ]
