# Generated by Django 3.1.4 on 2020-12-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_tipology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_issue', models.CharField(choices=[('1', 'Extorcao'), ('2', 'Obstaculos sociais ou culturais'), ('3', 'Distancia'), ('4', 'Infrastructure'), ('5', 'Seguranca'), ('6', 'Physical vulnerability'), ('7', 'Resources'), ('8', 'other'), ('9', 'Motivos Politicos'), ('10', 'Fraude'), ('11', 'Corrupcao'), ('12', 'Desvio'), ('13', 'Never received assistance')], help_text='Sub Category Issue', max_length=2, verbose_name='Sub Category Issue')),
                ('casetipology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.casetipology')),
            ],
            options={
                'verbose_name': 'subcategoryissue',
                'verbose_name_plural': 'subcategoryissues',
            },
        ),
    ]
