# Generated by Django 3.1.4 on 2020-12-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_tipology', '0002_subcategoryissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryissue',
            name='casetipology',
        ),
        migrations.AddField(
            model_name='subcategoryissue',
            name='subcategory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='case_tipology.subcategory'),
            preserve_default=False,
        ),
    ]
