# Generated by Django 3.1.4 on 2020-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_tipology', '0003_auto_20201209_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetipology',
            name='category',
            field=models.TextField(help_text='Case Category', verbose_name='Case Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.TextField(help_text='Sub Category', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='subcategoryissue',
            name='subcategory_issue',
            field=models.TextField(help_text='Sub Category Issue', verbose_name='Sub Category Issue'),
        ),
    ]
