# Generated by Django 3.1.4 on 2020-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_tipology', '0004_auto_20201209_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='casetipology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.casetipology'),
        ),
        migrations.AlterField(
            model_name='subcategoryissue',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_tipology.subcategory'),
        ),
    ]
